name: Marshall McLuhan Center
favicon: null
layout_spectrum: 0.5544305895455182
typography_spectrum: 0.16303356387652457
title: Marshall McLuhan Center
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.10863123997114599
  lightness: 0.9924657698720694
  saturation: 0.2912978797685355
  rhythmicContrast: 0.024064561584964395
purpose: []
